import type { Column } from "./column";
import type { GenericTableStructure } from "./generic-table";

export default interface InfoboxGameStructure extends GenericTableStructure {
    "_pageName": Column,
    "Cover": Column,
    "Cover_URL": Column,
    "Developers": Column<string[]>,
    "Porters_PC_booter": Column<string[]>,
    "Porters_DOS": Column<string[]>,
    "Porters_Windows_3x": Column<string[]>,
    "Porters_Windows": Column<string[]>,
    "Porters_Mac_OS": Column<string[]>,
    "Porters_OS_X": Column<string[]>,
    "Porters_Linux": Column<string[]>,
    "Publishers": Column<string[]>,
    "Engines": Column<string[]>,
    "Available_on": Column<string[]>,
    "Released": Column<Date[], ";">,
    "Released_PC_booter": Column<Date>,
    "Released_DOS": Column<Date>,
    "Released_Windows_3x": Column<Date>,
    "Released_Windows": Column<Date>,
    "Released_Mac_OS": Column<Date>,
    "Released_OS_X": Column<Date>,
    "Released_Linux": Column<Date>,
    "Wrappers": Column<string[]>,
    "Wrappers_Windows_3x": Column<string[]>,
    "Wrappers_Windows": Column<string[]>,
    "Wrappers_OS_X": Column<string[]>,
    "Wrappers_Linux": Column<string[]>,
    "Monetization": Column<string[]>,
    "Microtransactions": Column<string[]>,
    "Modes": Column<string[]>,
    "Pacing": Column<string[]>,
    "Perspectives": Column<string[]>,
    "Controls": Column<string[]>,
    "Genres": Column<string[]>,
    "Sports": Column<string[]>,
    "Vehicles": Column<string[]>,
    "Art_styles": Column<string[]>,
    "Themes": Column<string[]>,
    "Series": Column<string[]>,
    "Steam_AppID": Column<number[]>,
    "GOGcom_ID": Column<number[]>,
    "StrategyWiki": Column
    "Wikipedia": Column
    "License": Column
}
